on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deny:
    uses: ./.github/workflows/_deny.yaml

  check:
    uses: ./.github/workflows/_check.yaml

  test:
    uses: ./.github/workflows/_test.yaml
    needs: check

  release_pr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_release_pr.yaml
    permissions:
      contents: write
      pull-requests: write

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_release.yaml
    needs: ["deny", "test"]
    permissions:
      contents: write
      pull-requests: read
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
